accounts/urls.py
from django.conf.urls import url
from . import views
app_name = 'accounts'
urlpatterns = [
    url(r'^get-phone-number/', views.get_phone_number, name='register'),
    url(r'^check-otp/', views.check_otp, name='check-otp'),
    url(r'^get-password/', views.get_password, name='get-password')
]

shonirvor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .views import home


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls')),
    url(r'^services/', include('services.urls')),
    url(r'^profile/', include('userprofile.urls')),

    url(r'^$', home, name='home')

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Shonirvor</title>
        <link rel="shortcut icon" href="{% static 'img/pro.jpg' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">

        <!-- Bootstrap -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        {#css for specific pages#}
        {% block css %}
        {% endblock %}
    </head>

    <body>
        {% include 'snippets/header.html' %}

        {% block content %}
        {% endblock %}

        {% include 'snippets/footer.html' %}

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        {#javascirpts for specific pages#}
        {% block javascript %}
        {% endblock %}
    </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>this is home page</h1>
    <a href="{% url 'accounts:register' %}">রেজিষ্ট্রেশন করুন</a>
    <p>services</p>
    <ul>
        {% for service in services %}
            <li>{{ service.service_name }}</li>
        {% endfor %}
    </ul>
{% endblock %}